/* ————— Hikayat · Vocabulary & Spaced Repetition Core Data ————————————————
   Foundational Arabic vocabulary for young learners drawn from the 8 storybooks
   and Qaida stages.
   ========================================================================= */
'use strict';

const VOCAB_CATEGORIES = [
  { id: 'all',        ar: 'الْكُلّ',       en: 'All Words',      emoji: '🌟', color: '#F09CB1' },
  { id: 'characters', ar: 'شَخْصِيَّات',   en: 'Characters',     emoji: '👥', color: '#7FB0D6' },
  { id: 'home',       ar: 'فِي الْبَيْت',  en: 'Around House',   emoji: '🏠', color: '#E8A33D' },
  { id: 'food',       ar: 'طَعَام',        en: 'Food & Drink',   emoji: '🍎', color: '#7BC08F' },
  { id: 'nature',     ar: 'طَبِيعَة',      en: 'Nature & Sky',   emoji: '🌙', color: '#5B8C7B' },
  { id: 'core',       ar: 'كَلِمَات مُهِمَّة', en: 'Core Words', emoji: '✨', color: '#A98CD0' },
];

const VOCAB_WORDS = [
  /* ————— 1. Characters & Animals ————— */
  {
    id: 'adam',
    ar: 'آدَم',
    en: 'Adam',
    cat: 'characters',
    icon: 'adam',
    level: 1,
    book: 'who-house',
    exAr: 'آدَمُ فِي الْبَيْتِ',
    exEn: 'Adam is in the house',
  },
  {
    id: 'lulu',
    ar: 'لُولُو',
    en: 'Lulu',
    cat: 'characters',
    icon: 'cat2',
    level: 1,
    book: 'lulu-saghir',
    exAr: 'لُولُو قِطَّةٌ صَغِيرَةٌ',
    exEn: 'Lulu is a little cat',
  },
  {
    id: 'mama',
    ar: 'مَامَا',
    en: 'Mama',
    cat: 'characters',
    icon: 'mama',
    level: 1,
    book: 'who-house',
    exAr: 'مَامَا فِي الْمَطْبَخِ',
    exEn: 'Mama is in the kitchen',
  },
  {
    id: 'baba',
    ar: 'بَابَا',
    en: 'Baba',
    cat: 'characters',
    icon: 'baba',
    level: 1,
    book: 'who-house',
    exAr: 'بَابَا يَقْرَأُ كِتَابًا',
    exEn: 'Baba is reading a book',
  },
  {
    id: 'maryam',
    ar: 'مَرْيَم',
    en: 'Maryam',
    cat: 'characters',
    icon: 'maryam',
    level: 1,
    book: 'who-house',
    exAr: 'مَرْيَمُ فِي الْغُرْفَةِ',
    exEn: 'Maryam is in the room',
  },
  {
    id: 'arnab',
    ar: 'أَرْنَب',
    en: 'Rabbit',
    cat: 'characters',
    icon: 'arnab',
    level: 2,
    book: 'arnab-qird',
    exAr: 'الْأَرْنَبُ يَجْرِي سَرِيعًا',
    exEn: 'The rabbit runs fast',
  },
  {
    id: 'qird',
    ar: 'قِرْد',
    en: 'Monkey',
    cat: 'characters',
    icon: 'qird',
    level: 2,
    book: 'arnab-qird',
    exAr: 'الْقِرْدُ يَأْكُلُ الْمَوْزَ',
    exEn: 'The monkey eats the banana',
  },
  {
    id: 'feel',
    ar: 'فِيل',
    en: 'Elephant',
    cat: 'characters',
    icon: 'elephant',
    level: 1,
    book: 'madha-turid',
    exAr: 'هَذَا فِيلٌ كَبِيرٌ',
    exEn: 'This is a big elephant',
  },
  {
    id: 'faar',
    ar: 'فَأْر',
    en: 'Mouse',
    cat: 'characters',
    icon: 'mouse',
    level: 1,
    book: 'madha-turid',
    exAr: 'فَأْرٌ صَغِيرٌ جِدًّا',
    exEn: 'A very small mouse',
  },

  /* ————— 2. Around the House ————— */
  {
    id: 'bayt',
    ar: 'بَيْت',
    en: 'House',
    cat: 'home',
    icon: 'dar',
    level: 1,
    book: 'who-house',
    exAr: 'هَذَا بَيْتٌ جَمِيلٌ',
    exEn: 'This is a beautiful house',
  },
  {
    id: 'kitab',
    ar: 'كِتَاب',
    en: 'Book',
    cat: 'home',
    icon: 'kitab',
    level: 1,
    book: 'madha-turid',
    exAr: 'أُرِيدُ كِتَابًا',
    exEn: 'I want a book',
  },
  {
    id: 'matbakh',
    ar: 'مَطْبَخ',
    en: 'Kitchen',
    cat: 'home',
    icon: 'kitchen',
    level: 2,
    book: 'who-house',
    exAr: 'الْمَطْبَخُ نَظِيفٌ',
    exEn: 'The kitchen is clean',
  },
  {
    id: 'ghurfa',
    ar: 'غُرْفَة',
    en: 'Room',
    cat: 'home',
    icon: 'room',
    level: 2,
    book: 'who-house',
    exAr: 'غُرْفَةُ نَوْمٍ',
    exEn: 'A bedroom',
  },
  {
    id: 'sarir',
    ar: 'سَرِير',
    en: 'Bed',
    cat: 'home',
    icon: 'bed',
    level: 2,
    book: 'lulu-1',
    exAr: 'لُولُو فَوْقَ السَّرِيرِ',
    exEn: 'Lulu is on the bed',
  },
  {
    id: 'kursi',
    ar: 'كُرْسِيّ',
    en: 'Chair',
    cat: 'home',
    icon: 'chair',
    level: 2,
    book: 'lulu-1',
    exAr: 'كُرْسِيٌّ فِي الْغُرْفَةِ',
    exEn: 'A chair in the room',
  },
  {
    id: 'hidaa',
    ar: 'حِذَاء',
    en: 'Shoe',
    cat: 'home',
    icon: 'sneaker',
    level: 3,
    book: 'hidaa-1',
    exAr: 'أَيْنَ حِذَائِي؟',
    exEn: 'Where is my shoe?',
  },
  {
    id: 'sundooq',
    ar: 'صُنْدُوق',
    en: 'Box',
    cat: 'home',
    icon: 'box',
    level: 2,
    book: 'lulu-1',
    exAr: 'صُنْدُوقٌ صَغِيرٌ',
    exEn: 'A small box',
  },
  {
    id: 'masjid',
    ar: 'مَسْجِد',
    en: 'Masjid',
    cat: 'home',
    icon: 'masjid',
    level: 3,
    book: 'hidaa-1',
    exAr: 'نَمْشِي إِلَى الْمَسْجِدِ',
    exEn: 'We walk to the masjid',
  },
  {
    id: 'fursha',
    ar: 'فُرْشَاة',
    en: 'Brush',
    cat: 'home',
    icon: 'brush',
    level: 4,
    book: 'yawmi-1',
    exAr: 'فُرْشَاةُ الْأَسْنَانِ',
    exEn: 'Toothbrush',
  },

  /* ————— 3. Food & Drink ————— */
  {
    id: 'mawz',
    ar: 'مَوْز',
    en: 'Banana',
    cat: 'food',
    icon: 'mawz',
    level: 1,
    book: 'madha-turid',
    exAr: 'أُرِيدُ مَوْزًا',
    exEn: 'I want a banana',
  },
  {
    id: 'samak',
    ar: 'سَمَك',
    en: 'Fish',
    cat: 'food',
    icon: 'fish',
    level: 1,
    book: 'madha-turid',
    exAr: 'لُولُو تُحِبُّ السَّمَكَ',
    exEn: 'Lulu loves fish',
  },
  {
    id: 'dajaj',
    ar: 'دَجَاج',
    en: 'Chicken',
    cat: 'food',
    icon: 'chicken',
    level: 1,
    book: 'madha-turid',
    exAr: 'دَجَاجٌ لَذِيذٌ',
    exEn: 'Delicious chicken',
  },
  {
    id: 'aseer',
    ar: 'عَصِير',
    en: 'Juice',
    cat: 'food',
    icon: 'juice',
    level: 1,
    book: 'madha-turid',
    exAr: 'عَصِيرُ بُرْتُقَالٍ',
    exEn: 'Orange juice',
  },
  {
    id: 'jazar',
    ar: 'جَزَر',
    en: 'Carrot',
    cat: 'food',
    icon: 'jazar',
    level: 2,
    book: 'arnab-qird',
    exAr: 'جَزَرٌ طَازَجٌ',
    exEn: 'Fresh carrot',
  },
  {
    id: 'futur',
    ar: 'فُطُور',
    en: 'Breakfast',
    cat: 'food',
    icon: 'breakfast',
    level: 4,
    book: 'yawmi-1',
    exAr: 'نَتَنَاوَلُ الْفُطُورَ مَعًا',
    exEn: 'We eat breakfast together',
  },

  /* ————— 4. Nature & Sky ————— */
  {
    id: 'qamar',
    ar: 'قَمَر',
    en: 'Moon',
    cat: 'nature',
    icon: 'qamar',
    level: 2,
    book: 'qamar-1',
    exAr: 'الْقَمَرُ فِي السَّمَاءِ',
    exEn: 'The moon is in the sky',
  },
  {
    id: 'shams',
    ar: 'شَمْس',
    en: 'Sun',
    cat: 'nature',
    icon: 'sun',
    level: 3,
    book: 'yawmi-1',
    exAr: 'الشَّمْسُ سَاطِعَةٌ',
    exEn: 'The sun is shining',
  },
  {
    id: 'najm',
    ar: 'نَجْم',
    en: 'Star',
    cat: 'nature',
    icon: 'najm',
    level: 2,
    book: 'qamar-1',
    exAr: 'نَجْمٌ يَلْمَعُ',
    exEn: 'A shining star',
  },
  {
    id: 'tayr',
    ar: 'طَيْر',
    en: 'Bird',
    cat: 'nature',
    icon: 'tayr',
    level: 2,
    book: 'qamar-1',
    exAr: 'طَيْرٌ فَوْقَ الشَّجَرَةِ',
    exEn: 'A bird on the tree',
  },
  {
    id: 'sahab',
    ar: 'سَحَاب',
    en: 'Cloud',
    cat: 'nature',
    icon: 'sahab',
    level: 2,
    book: 'qamar-1',
    exAr: 'سَحَابٌ فِي السَّمَاءِ',
    exEn: 'Clouds in the sky',
  },
  {
    id: 'layl',
    ar: 'لَيْل',
    en: 'Night',
    cat: 'nature',
    icon: 'layl',
    level: 2,
    book: 'qamar-1',
    exAr: 'لَيْلٌ هَادِئٌ',
    exEn: 'A calm night',
  },

  /* ————— 5. Core Words & Qualities ————— */
  {
    id: 'hadha',
    ar: 'هَذَا',
    en: 'This (m.)',
    cat: 'core',
    icon: 'rel_this',
    level: 1,
    book: 'madha-turid',
    exAr: 'هَذَا بَيْتِي',
    exEn: 'This is my house',
  },
  {
    id: 'hadhihi',
    ar: 'هَذِهِ',
    en: 'This (f.)',
    cat: 'core',
    icon: 'rel_this_f',
    level: 1,
    book: 'lulu-saghir',
    exAr: 'هَذِهِ لُولُو',
    exEn: 'This is Lulu',
  },
  {
    id: 'kabir',
    ar: 'كَبِير',
    en: 'Big',
    cat: 'core',
    icon: 'rel_big',
    level: 1,
    book: 'madha-turid',
    exAr: 'فِيلٌ كَبِيرٌ',
    exEn: 'A big elephant',
  },
  {
    id: 'saghir',
    ar: 'صَغِير',
    en: 'Small',
    cat: 'core',
    icon: 'rel_small',
    level: 1,
    book: 'lulu-saghir',
    exAr: 'لُولُو صَغِيرَةٌ',
    exEn: 'Lulu is small',
  },
  {
    id: 'jameel',
    ar: 'جَمِيل',
    en: 'Beautiful',
    cat: 'core',
    icon: 'heart2',
    level: 1,
    book: 'lulu-saghir',
    exAr: 'بَيْتٌ جَمِيلٌ',
    exEn: 'A beautiful house',
  },
  {
    id: 'ayna',
    ar: 'أَيْنَ',
    en: 'Where?',
    cat: 'core',
    icon: 'rel_where',
    level: 2,
    book: 'qamar-1',
    exAr: 'أَيْنَ لُولُو؟',
    exEn: 'Where is Lulu?',
  },
  {
    id: 'madha',
    ar: 'مَاذَا',
    en: 'What?',
    cat: 'core',
    icon: 'rel_want',
    level: 1,
    book: 'madha-turid',
    exAr: 'مَاذَا تُرِيدُ؟',
    exEn: 'What do you want?',
  },
  {
    id: 'man',
    ar: 'مَنْ',
    en: 'Who?',
    cat: 'core',
    icon: 'rel_who',
    level: 2,
    book: 'who-house',
    exAr: 'مَنْ فِي الْبَيْتِ؟',
    exEn: 'Who is in the house?',
  },
  {
    id: 'ureedu',
    ar: 'أُرِيدُ',
    en: 'I want',
    cat: 'core',
    icon: 'rel_want',
    level: 1,
    book: 'madha-turid',
    exAr: 'أُرِيدُ عَصِيرًا',
    exEn: 'I want juice',
  },
  {
    id: 'fee',
    ar: 'فِي',
    en: 'In / Inside',
    cat: 'core',
    icon: 'rel_in',
    level: 2,
    book: 'who-house',
    exAr: 'فِي الْبَيْتِ',
    exEn: 'In the house',
  },
  {
    id: 'fawqa',
    ar: 'فَوْقَ',
    en: 'On / Above',
    cat: 'core',
    icon: 'rel_on',
    level: 2,
    book: 'lulu-1',
    exAr: 'فَوْقَ السَّرِيرِ',
    exEn: 'On top of the bed',
  },
  {
    id: 'tahta',
    ar: 'تَحْتَ',
    en: 'Under',
    cat: 'core',
    icon: 'rel_under',
    level: 2,
    book: 'lulu-1',
    exAr: 'تَحْتَ الْكُرْسِيِّ',
    exEn: 'Under the chair',
  },
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { VOCAB_CATEGORIES, VOCAB_WORDS };
}
