/* ————— Hikayat · Vocabulary & Spaced Repetition Core Data ————————————————
   Authentic foundational Arabic vocabulary for young learners (ages 3–6).
   Strict rule: Pure vocabulary words only (animals, household items, food,
   nature, core qualities & prepositions) — no proper names or family titles.
   ========================================================================= */
'use strict';

const VOCAB_CATEGORIES = [
  { id: 'all',     ar: 'الْكُلّ',          en: 'All Words',     emoji: '🌟', color: '#F09CB1' },
  { id: 'animals', ar: 'حَيَوَانَات',      en: 'Animals',       emoji: '🐰', color: '#7FB0D6' },
  { id: 'home',    ar: 'فِي الْبَيْت',     en: 'Around House',  emoji: '🏠', color: '#E8A33D' },
  { id: 'food',    ar: 'طَعَام وَشَرَاب',  en: 'Food & Drink',  emoji: '🍎', color: '#7BC08F' },
  { id: 'nature',  ar: 'طَبِيعَة',         en: 'Nature & Sky',  emoji: '🌙', color: '#5B8C7B' },
  { id: 'core',    ar: 'أَفْعَال وَصِفَات', en: 'Core Concepts', emoji: '✨', color: '#A98CD0' },
];

const VOCAB_WORDS = [
  /* ————— 1. Animals (حَيَوَانَات) ————— */
  {
    id: 'arnab',
    ar: 'أَرْنَب',
    en: 'Rabbit',
    cat: 'animals',
    icon: 'arnab',
    level: 2,
    book: 'arnab-qird',
    exAr: 'الْأَرْنَبُ يَجْرِي سَرِيعًا',
    exEn: 'The rabbit runs fast',
  },
  {
    id: 'qird',
    ar: 'قِرْد',
    en: 'Monkey',
    cat: 'animals',
    icon: 'qird',
    level: 2,
    book: 'arnab-qird',
    exAr: 'الْقِرْدُ يَأْكُلُ الْمَوْزَ',
    exEn: 'The monkey eats the banana',
  },
  {
    id: 'qitta',
    ar: 'قِطَّة',
    en: 'Cat',
    cat: 'animals',
    icon: 'cat2',
    level: 1,
    book: 'lulu-saghir',
    exAr: 'قِطَّةٌ صَغِيرَةٌ جَمِيلَةٌ',
    exEn: 'A beautiful small cat',
  },
  {
    id: 'feel',
    ar: 'فِيل',
    en: 'Elephant',
    cat: 'animals',
    icon: 'feel',
    level: 1,
    book: 'madha-turid',
    exAr: 'هَذَا فِيلٌ كَبِيرٌ',
    exEn: 'This is a big elephant',
  },
  {
    id: 'faar',
    ar: 'فَأْر',
    en: 'Mouse',
    cat: 'animals',
    icon: 'faar',
    level: 1,
    book: 'madha-turid',
    exAr: 'فَأْرٌ صَغِيرٌ جِدًّا',
    exEn: 'A very small mouse',
  },
  {
    id: 'samak',
    ar: 'سَمَك',
    en: 'Fish',
    cat: 'animals',
    icon: 'samak',
    level: 1,
    book: 'madha-turid',
    exAr: 'سَمَكٌ فِي الْمَاءِ',
    exEn: 'Fish in the water',
  },
  {
    id: 'dajaj',
    ar: 'دَجَاج',
    en: 'Chicken',
    cat: 'animals',
    icon: 'dajaj',
    level: 1,
    book: 'madha-turid',
    exAr: 'دَجَاجٌ لَذِيذٌ',
    exEn: 'Delicious chicken',
  },
  {
    id: 'tayr',
    ar: 'طَيْر',
    en: 'Bird',
    cat: 'animals',
    icon: 'tayr',
    level: 2,
    book: 'qamar-1',
    exAr: 'طَيْرٌ فَوْقَ الشَّجَرَةِ',
    exEn: 'A bird on the tree',
  },
  {
    id: 'ghurab',
    ar: 'غُرَاب',
    en: 'Crow',
    cat: 'animals',
    icon: 'ghurab',
    level: 2,
    book: 'stories-text',
    exAr: 'غُرَابٌ أَسْوَدُ ذَكِيٌّ',
    exEn: 'A clever black crow',
  },
  {
    id: 'hoot',
    ar: 'حُوت',
    en: 'Whale',
    cat: 'animals',
    icon: 'hoot',
    level: 2,
    book: 'qaida',
    exAr: 'حُوتٌ فِي الْبَحْرِ',
    exEn: 'A whale in the sea',
  },
  {
    id: 'difda',
    ar: 'ضِفْدَع',
    en: 'Frog',
    cat: 'animals',
    icon: 'difda',
    level: 2,
    book: 'qaida',
    exAr: 'ضِفْدَعٌ أَخْضَرُ صَغِيرٌ',
    exEn: 'A small green frog',
  },
  {
    id: 'dhib',
    ar: 'ذِئْب',
    en: 'Wolf',
    cat: 'animals',
    icon: 'dhib',
    level: 2,
    book: 'qaida',
    exAr: 'ذِئْبٌ فِي الْغَابَةِ',
    exEn: 'A wolf in the forest',
  },

  /* ————— 2. Around the House (فِي الْبَيْت) ————— */
  {
    id: 'bayt',
    ar: 'بَيْت',
    en: 'House',
    cat: 'home',
    icon: 'dar',
    level: 1,
    book: 'who-house',
    exAr: 'هَذَا بَيْتٌ جَمِيلٌ',
    exEn: 'This is a beautiful house',
  },
  {
    id: 'bab',
    ar: 'بَاب',
    en: 'Door',
    cat: 'home',
    icon: 'bab',
    level: 1,
    book: 'who-house',
    exAr: 'بَابُ الْبَيْتِ مَفْتُوحٌ',
    exEn: 'The house door is open',
  },
  {
    id: 'kitab',
    ar: 'كِتَاب',
    en: 'Book',
    cat: 'home',
    icon: 'kitab',
    level: 1,
    book: 'madha-turid',
    exAr: 'أُرِيدُ كِتَابًا',
    exEn: 'I want a book',
  },
  {
    id: 'matbakh',
    ar: 'مَطْبَخ',
    en: 'Kitchen',
    cat: 'home',
    icon: 'kitchen',
    level: 2,
    book: 'who-house',
    exAr: 'الْمَطْبَخُ نَظِيفٌ',
    exEn: 'The kitchen is clean',
  },
  {
    id: 'ghurfa',
    ar: 'غُرْفَة',
    en: 'Room',
    cat: 'home',
    icon: 'room',
    level: 2,
    book: 'who-house',
    exAr: 'غُرْفَةُ نَوْمٍ',
    exEn: 'A bedroom',
  },
  {
    id: 'sarir',
    ar: 'سَرِير',
    en: 'Bed',
    cat: 'home',
    icon: 'bed',
    level: 2,
    book: 'lulu-1',
    exAr: 'فَوْقَ السَّرِيرِ',
    exEn: 'On top of the bed',
  },
  {
    id: 'kursi',
    ar: 'كُرْسِيّ',
    en: 'Chair',
    cat: 'home',
    icon: 'chair',
    level: 2,
    book: 'lulu-1',
    exAr: 'كُرْسِيٌّ فِي الْغُرْفَةِ',
    exEn: 'A chair in the room',
  },
  {
    id: 'hidaa',
    ar: 'حِذَاء',
    en: 'Shoe',
    cat: 'home',
    icon: 'hidhaa',
    level: 3,
    book: 'hidaa-1',
    exAr: 'أَيْنَ حِذَائِي؟',
    exEn: 'Where is my shoe?',
  },
  {
    id: 'sundooq',
    ar: 'صُنْدُوق',
    en: 'Box',
    cat: 'home',
    icon: 'box',
    level: 2,
    book: 'lulu-1',
    exAr: 'صُنْدُوقٌ صَغِيرٌ',
    exEn: 'A small box',
  },
  {
    id: 'masjid',
    ar: 'مَسْجِد',
    en: 'Masjid',
    cat: 'home',
    icon: 'masjid',
    level: 3,
    book: 'hidaa-1',
    exAr: 'نَمْشِي إِلَى الْمَسْجِدِ',
    exEn: 'We walk to the masjid',
  },
  {
    id: 'fursha',
    ar: 'فُرْشَاة',
    en: 'Brush',
    cat: 'home',
    icon: 'fursha',
    level: 4,
    book: 'yawmi-1',
    exAr: 'فُرْشَاةُ الْأَسْنَانِ',
    exEn: 'Toothbrush',
  },
  {
    id: 'walad',
    ar: 'وَلَد',
    en: 'Boy',
    cat: 'home',
    icon: 'walad',
    level: 2,
    book: 'qaida',
    exAr: 'وَلَدٌ طَيِّبٌ',
    exEn: 'A good boy',
  },
  {
    id: 'bint',
    ar: 'بِنْت',
    en: 'Girl',
    cat: 'home',
    icon: 'bint',
    level: 2,
    book: 'qaida',
    exAr: 'بِنْتٌ طَيِّبَةٌ',
    exEn: 'A kind girl',
  },

  /* ————— 3. Food & Drink (طَعَام وَشَرَاب) ————— */
  {
    id: 'mawz',
    ar: 'مَوْز',
    en: 'Banana',
    cat: 'food',
    icon: 'mawz',
    level: 1,
    book: 'madha-turid',
    exAr: 'أُرِيدُ مَوْزًا',
    exEn: 'I want a banana',
  },
  {
    id: 'jazar',
    ar: 'جَزَر',
    en: 'Carrot',
    cat: 'food',
    icon: 'jazar',
    level: 2,
    book: 'arnab-qird',
    exAr: 'جَزَرٌ طَازَجٌ',
    exEn: 'Fresh carrot',
  },
  {
    id: 'khubz',
    ar: 'خُبْز',
    en: 'Bread',
    cat: 'food',
    icon: 'khubz',
    level: 2,
    book: 'qaida',
    exAr: 'خُبْزٌ سَاخِنٌ لَذِيذٌ',
    exEn: 'Delicious warm bread',
  },
  {
    id: 'aseer',
    ar: 'عَصِير',
    en: 'Juice',
    cat: 'food',
    icon: 'aseer',
    level: 1,
    book: 'madha-turid',
    exAr: 'عَصِيرُ بُرْتُقَالٍ',
    exEn: 'Orange juice',
  },
  {
    id: 'maa',
    ar: 'مَاء',
    en: 'Water',
    cat: 'food',
    icon: 'maa',
    level: 1,
    book: 'qaida',
    exAr: 'مَاءٌ عَذْبٌ بَارِدٌ',
    exEn: 'Cool sweet water',
  },
  {
    id: 'zaytoon',
    ar: 'زَيْتُون',
    en: 'Olives',
    cat: 'food',
    icon: 'zaytoon',
    level: 2,
    book: 'qaida',
    exAr: 'زَيْتُونٌ أَخْضَرُ',
    exEn: 'Green olives',
  },
  {
    id: 'thamar',
    ar: 'ثَمَر',
    en: 'Fruit',
    cat: 'food',
    icon: 'thamar',
    level: 2,
    book: 'qaida',
    exAr: 'ثَمَرٌ طَيِّبٌ',
    exEn: 'Good fruit',
  },
  {
    id: 'futur',
    ar: 'فُطُور',
    en: 'Breakfast',
    cat: 'food',
    icon: 'futur',
    level: 4,
    book: 'yawmi-1',
    exAr: 'نَتَنَاوَلُ الْفُطُورَ مَعًا',
    exEn: 'We eat breakfast together',
  },
  {
    id: 'taam',
    ar: 'طَعَام',
    en: 'Food',
    cat: 'food',
    icon: 'taam',
    level: 2,
    book: 'madha-turid',
    exAr: 'طَعَامٌ لَذِيذٌ',
    exEn: 'Delicious food',
  },

  /* ————— 4. Nature & Sky (طَبِيعَة) ————— */
  {
    id: 'qamar',
    ar: 'قَمَر',
    en: 'Moon',
    cat: 'nature',
    icon: 'qamar',
    level: 2,
    book: 'qamar-1',
    exAr: 'الْقَمَرُ فِي السَّمَاءِ',
    exEn: 'The moon is in the sky',
  },
  {
    id: 'shams',
    ar: 'شَمْس',
    en: 'Sun',
    cat: 'nature',
    icon: 'shams',
    level: 3,
    book: 'yawmi-1',
    exAr: 'الشَّمْسُ سَاطِعَةٌ',
    exEn: 'The sun is shining',
  },
  {
    id: 'najm',
    ar: 'نَجْم',
    en: 'Star',
    cat: 'nature',
    icon: 'najm',
    level: 2,
    book: 'qamar-1',
    exAr: 'نَجْمٌ يَلْمَعُ',
    exEn: 'A shining star',
  },
  {
    id: 'sahab',
    ar: 'سَحَاب',
    en: 'Cloud',
    cat: 'nature',
    icon: 'sahab',
    level: 2,
    book: 'qamar-1',
    exAr: 'سَحَابٌ فِي السَّمَاءِ',
    exEn: 'Clouds in the sky',
  },
  {
    id: 'layl',
    ar: 'لَيْل',
    en: 'Night',
    cat: 'nature',
    icon: 'layl',
    level: 2,
    book: 'qamar-1',
    exAr: 'لَيْلٌ هَادِئٌ',
    exEn: 'A calm night',
  },
  {
    id: 'samaa',
    ar: 'سَمَاء',
    en: 'Sky',
    cat: 'nature',
    icon: 'samaa',
    level: 2,
    book: 'qamar-1',
    exAr: 'السَّمَاءُ زَرْقَاءُ',
    exEn: 'The sky is blue',
  },
  {
    id: 'jabal',
    ar: 'جَبَل',
    en: 'Mountain',
    cat: 'nature',
    icon: 'jabal',
    level: 2,
    book: 'qaida',
    exAr: 'جَبَلٌ عَالٍ',
    exEn: 'A tall mountain',
  },
  {
    id: 'ard',
    ar: 'أَرْض',
    en: 'Earth',
    cat: 'nature',
    icon: 'ard',
    level: 2,
    book: 'qaida',
    exAr: 'الْأَرْضُ خَضْرَاءُ',
    exEn: 'The earth is green',
  },
  {
    id: 'reeh',
    ar: 'رِيح',
    en: 'Wind',
    cat: 'nature',
    icon: 'reeh',
    level: 2,
    book: 'qaida',
    exAr: 'رِيحٌ طَيِّبَةٌ',
    exEn: 'A gentle breeze',
  },

  /* ————— 5. Core Concepts, Adjectives & Verbs (أَفْعَال وَصِفَات) ————— */
  {
    id: 'kabir',
    ar: 'كَبِير',
    en: 'Big',
    cat: 'core',
    icon: 'kabir',
    level: 1,
    book: 'madha-turid',
    exAr: 'فِيلٌ كَبِيرٌ',
    exEn: 'A big elephant',
  },
  {
    id: 'saghir',
    ar: 'صَغِير',
    en: 'Small',
    cat: 'core',
    icon: 'saghir',
    level: 1,
    book: 'lulu-saghir',
    exAr: 'عُصْفُورٌ صَغِيرٌ',
    exEn: 'A small sparrow',
  },
  {
    id: 'jameel',
    ar: 'جَمِيل',
    en: 'Beautiful',
    cat: 'core',
    icon: 'jameel',
    level: 1,
    book: 'lulu-saghir',
    exAr: 'بَيْتٌ جَمِيلٌ',
    exEn: 'A beautiful house',
  },
  {
    id: 'ladheedh',
    ar: 'لَذِيذ',
    en: 'Delicious',
    cat: 'core',
    icon: 'ladheedh',
    level: 1,
    book: 'madha-turid',
    exAr: 'طَعَامٌ لَذِيذٌ',
    exEn: 'Delicious food',
  },
  {
    id: 'nazheef',
    ar: 'نَظِيف',
    en: 'Clean',
    cat: 'core',
    icon: 'nazheef',
    level: 2,
    book: 'who-house',
    exAr: 'الْمَطْبَخُ نَظِيفٌ',
    exEn: 'The kitchen is clean',
  },
  {
    id: 'saree',
    ar: 'سَرِيع',
    en: 'Fast',
    cat: 'core',
    icon: 'saree',
    level: 2,
    book: 'arnab-qird',
    exAr: 'الْأَرْنَبُ سَرِيعٌ',
    exEn: 'The rabbit is fast',
  },
  {
    id: 'hadha',
    ar: 'هَذَا',
    en: 'This (m.)',
    cat: 'core',
    icon: 'hadha',
    level: 1,
    book: 'madha-turid',
    exAr: 'هَذَا بَيْتِي',
    exEn: 'This is my house',
  },
  {
    id: 'hadhihi',
    ar: 'هَذِهِ',
    en: 'This (f.)',
    cat: 'core',
    icon: 'hadhihi',
    level: 1,
    book: 'lulu-saghir',
    exAr: 'هَذِهِ زَهْرَةٌ',
    exEn: 'This is a flower',
  },
  {
    id: 'ayna',
    ar: 'أَيْنَ',
    en: 'Where?',
    cat: 'core',
    icon: 'ayna',
    level: 2,
    book: 'qamar-1',
    exAr: 'أَيْنَ الْقَمَرُ؟',
    exEn: 'Where is the moon?',
  },
  {
    id: 'madha',
    ar: 'مَاذَا',
    en: 'What?',
    cat: 'core',
    icon: 'madha',
    level: 1,
    book: 'madha-turid',
    exAr: 'مَاذَا تُرِيدُ؟',
    exEn: 'What do you want?',
  },
  {
    id: 'ureedu',
    ar: 'أُرِيدُ',
    en: 'I want',
    cat: 'core',
    icon: 'ureedu',
    level: 1,
    book: 'madha-turid',
    exAr: 'أُرِيدُ مَاءً',
    exEn: 'I want water',
  },
  {
    id: 'fee',
    ar: 'فِي',
    en: 'In / Inside',
    cat: 'core',
    icon: 'fee',
    level: 2,
    book: 'who-house',
    exAr: 'فِي الْبَيْتِ',
    exEn: 'In the house',
  },
  {
    id: 'fawqa',
    ar: 'فَوْقَ',
    en: 'On / Above',
    cat: 'core',
    icon: 'fawqa',
    level: 2,
    book: 'lulu-1',
    exAr: 'فَوْقَ السَّرِيرِ',
    exEn: 'On top of the bed',
  },
  {
    id: 'tahta',
    ar: 'تَحْتَ',
    en: 'Under',
    cat: 'core',
    icon: 'tahta',
    level: 2,
    book: 'lulu-1',
    exAr: 'تَحْتَ الْكُرْسِيِّ',
    exEn: 'Under the chair',
  },
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { VOCAB_CATEGORIES, VOCAB_WORDS };
}
