/* Build data/surahs.json for the children's site, and fetch the REAL recitation.

     node scripts/gen-surahs.js  [path-to-arabiclanguage-checkout]

   WHY IT IS GENERATED AND NEVER HAND-WRITTEN. This is Qur'an. The text is
   copied byte-for-byte out of the grown-up site's data/verses.json, which is
   itself checked, and nothing here retypes, "tidies" or re-vowels a single
   letter. If the text is wrong the whole thing is worse than useless, so the
   only safe way to produce it is to copy it mechanically and to verify the copy
   afterwards (scripts/test-surahs.js re-reads the source and compares).

   THE AUDIO IS A REAL RECITER, NOT SYNTHESIS. Reza, 2026-08-31: "they should
   listen to real audio". Every other sound on this site is neural TTS, which is
   fine for بَاب and completely unacceptable for an ayah — tajweed, madd and
   waqf are the thing being taught. So the ayah and word clips are Mishary
   Rashid Alafasy, pulled from the same source the grown-up site uses and stored
   locally so they work on a plane.

   Output:
     data/surahs.json          exact text + word breakdowns + audio filenames
     audio/quran/a-<id>.mp3    one per ayah
     audio/quran/w-<id>.mp3    one per word
*/
const fs = require("fs"), path = require("path"), https = require("https");

const ROOT = path.join(__dirname, "..");
const SRC = process.argv[2] || path.join(ROOT, "..", "..", "..", "arabiclanguage");
const OUT_AUDIO = path.join(ROOT, "audio", "quran");

/* Al-Fatiha, then the ten shortest — by word count, which is what a child
   actually experiences as "short". */
const WANT = ["fatiha", "kawthar", "asr", "nasr", "ikhlas", "falaq", "quraysh", "fil", "nas", "kafirun", "masad"];

function read(f) {
  const p = path.join(SRC, "data", f);
  if (!fs.existsSync(p)) {
    console.error(`\nCannot find ${p}\nPass the path to your arabiclanguage checkout:\n  node scripts/gen-surahs.js /path/to/arabiclanguage\n`);
    process.exit(1);
  }
  return JSON.parse(fs.readFileSync(p, "utf8"));
}

const verses = read("verses.json");
const ayahAudio = read("ayah-audio.json");
const wordAudio = read("quran-word-audio.json");

/* the ayah-audio map is keyed by normalised text; match gen-audio.py's norm */
const norm = s => String(s || "")
  .replace(/[ً-ْٰـ]/g, "")
  .replace(/[أإآٱ]/g, "ا").replace(/ى/g, "ي").replace(/ة/g, "ه")
  .replace(/[^؀-ۿ\s]/g, "")
  .replace(/\s+/g, " ").trim();

function get(url) {
  return new Promise((res, rej) => {
    https.get(url, r => {
      if (r.statusCode >= 300 && r.statusCode < 400 && r.headers.location) {
        r.resume(); return get(r.headers.location).then(res, rej);
      }
      if (r.statusCode !== 200) { r.resume(); return rej(new Error(url + " -> " + r.statusCode)); }
      const chunks = []; r.on("data", c => chunks.push(c));
      r.on("end", () => res(Buffer.concat(chunks)));
    }).on("error", rej);
  });
}

async function fetchTo(url, file) {
  if (fs.existsSync(file) && fs.statSync(file).size > 500) return "skip";
  const buf = await get(url);
  if (buf.length < 500) throw new Error("suspiciously small: " + url);
  fs.writeFileSync(file, buf);
  return "got";
}

(async () => {
  fs.mkdirSync(OUT_AUDIO, { recursive: true });
  const out = { note: "GENERATED by scripts/gen-surahs.js from the grown-up site's verses.json. Do not hand-edit — the Arabic is copied, never retyped.", reciter: ayahAudio.reciter, surahs: [] };
  let gotA = 0, gotW = 0, missA = 0, missW = 0;

  for (const id of WANT) {
    const s = verses.surahs.find(x => x.id === id);
    if (!s) { console.error("!! no surah " + id + " in the source"); continue; }

    /* map[surahId][ayahIndex][wordIndex] -> [path, ...] */
    const wbw = wordAudio.map[id] || [];
    const ayat = [];

    for (let ai = 0; ai < s.verses.length; ai++) {
      const v = s.verses[ai];
      /* The recitation id is simply surah+ayah, zero-padded — 1:1 is 001001.
         Deriving it from the REF is exact. Looking it up by normalised text
         matched only 6 ayat out of 57, because this file's normalisation and
         the grown-up site's disagree about ة (that map keeps it, gen-audio.py
         folds it to ه) — and a near-miss on Qur'an audio is a silent wrong
         ayah, which is far worse than no audio. */
      const [sn, an] = v.ref.split(":").map(Number);
      const recId = String(sn).padStart(3, "0") + String(an).padStart(3, "0");
      const aFile = recId ? `a-${recId}.mp3` : null;
      if (recId) {
        try { if ((await fetchTo(ayahAudio.base + recId + ".mp3", path.join(OUT_AUDIO, aFile))) === "got") gotA++; }
        catch (e) { console.error("  ayah audio failed " + v.ref + ": " + e.message); missA++; }
      } else { missA++; console.error("  no recitation mapped for " + v.ref); }

      const words = [];
      for (let wj = 0; wj < v.words.length; wj++) {
        const w = v.words[wj];
        const cell = (wbw[ai] || [])[wj];
        const rel = Array.isArray(cell) ? String(cell[0] || "").trim() : String(cell || "").trim();
        let wFile = null;
        if (rel) {
          wFile = "w-" + rel.split("/").pop();
          try { if ((await fetchTo(wordAudio.base + rel, path.join(OUT_AUDIO, wFile))) === "got") gotW++; }
          catch (e) { missW++; wFile = null; }
        } else missW++;
        words.push({ ar: w[0], tr: w[1], en: w[2], audio: wFile });
      }
      ayat.push({ ref: v.ref, ar: v.ar, en: v.en, audio: aFile, words });
    }
    out.surahs.push({ id: s.id, n: s.n, name: s.name, nameEn: s.nameEn, ayat });
    console.log(`  ${s.id.padEnd(9)} ${String(s.ayat || ayat.length).padStart(2)} ayat, ${ayat.reduce((a, x) => a + x.words.length, 0)} words`);
  }

  fs.writeFileSync(path.join(ROOT, "data", "surahs.json"), JSON.stringify(out, null, 1));
  console.log(`\n${out.surahs.length} surahs written. audio: ${gotA} new ayah clips, ${gotW} new word clips; ${missA} ayat and ${missW} words without audio.`);
})();
